### ISSUE TITLE
Add storybook

### ISSUE THREAD

**Issue by alexedev** [kiwicom/stopovers#1]
will be resolved in https://github.com/kiwicom/stopovers/pull/10

**Comment by oreqizer** [comment]
Covered by https://github.com/kiwicom/stopovers/pull/10, however, there's some wild Next babel config going on.

**Comment by alexedev** [comment]
yes I know that it is already there, 

I added a fix in that MR

**Comment by alexedev** [comment]
fixed in https://github.com/kiwicom/stopovers/pull/10
