### ISSUE TITLE
Fix Language dropdown width

### ISSUE THREAD

**Issue by alexedev** [kiwicom/stopovers#235]
The width of the `Language` component on mobile, currently depends on the max width of the available options, instead of the width of the chosen option. I wrote the Nitrolib guys to see if this can be fixed there.

A [merge request](https://gitlab.skypicker.com/frontend/nitrolib/merge_requests/70) was created to fix the `Language` component on Nitrolib - update nitrolib after the merge - it should solve the issue.

**Comment by nglgzz** [comment]
The fix has been merged. We can integrate it by updating Nitrolib on the next release.
